services:
  - mysql:latest
test:5.6:
  image: php:5.6
  script:
    - find -type f -name "*.php" -exec php -l {} \; > find
    - bash -c 'grep -v "No syntax errors detected" find && exit 128 || exit 0'
    - rm -f find
test:7:
  image: php:7
  script:
    - find -type f -name "*.php" -exec php -l {} \; > find
    - bash -c 'grep -v "No syntax errors detected" find && exit 128 || exit 0'
    - rm -f find